### ISSUE TITLE
Error installing Windows 11

### ISSUE THREAD

**Issue by alekseybv** [SeppHansen/SLSS-CANAnalyser#1]
Fehler bei der Überprüfung der Systemkomponente Microsoft .NET Framework 4.5.2 (x86 und x64). Fehlermeldung:
"Die Installation von .NET Framework 4.5.2 wird auf diesem Betriebssystem nicht unterstützt. Wenden Sie sich an den Hersteller der Anwendung."

Result of checks for command 'DotNetFX452\NDP452-KB2901907-x86-x64-AllOS-DEU.exe' is 'Fail'
'Microsoft .NET Framework 4.5.2 (x86 und x64)' RunCheck result: Fail
A prerequisite failed for Package "Microsoft .NET Framework 4.5.2 (x86 und x64)"
Package failed with message "Die Installation von .NET Framework 4.5.2 wird auf diesem Betriebssystem nicht unterstützt. Wenden Sie sich an den Hersteller der Anwendung."

**Comment by SeppHansen** [comment]
Hi @alekseybv,
please check my bugfix of removing the explicit usage of .Net Framework 4.5.2 from the project on your Win11 system. I still use Win10 on all of my computers so I have no possibility to check if it works. Got my fingers crossed and hope it helps... 

kind regards and some early christmas wishes
Sebastian

**Comment by alekseybv** [comment]
Привет, @SeppHansen.
Да действительно теперь все работает.

Удачи Вам в ваших начинаниях. С наступающим Новым годом.
Алексей.
